apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    webhook: $slack-webhook-secret:webhook-url
  trigger.on-deployed: |
    - description: Application was successfully synced
      send:
        - slack
      when: app.status.operationState.phase in ['I did it']
  template.slack: |
    message: |
      *{{.app.metadata.name}}* was successfully deployed!!!!!


