apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    webhook: $argocd-notifications-secret:slack-webhook
  trigger.on-deployed: |
    - description: Application was successfully synced
      send:
        - slack
      when: app.status.operationState.phase in ['Succeeded']
  template.slack: |
    message: |
      *{{.app.metadata.name}}* was successfully deployed!!!
