apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    webhook: $slack-webhook-secret:url
  trigger.on-sync-succeeded: |
    - description: Application sync succeeded
      when: app.status.operationState.phase == 'Succeeded'
      send:
        - slack
  template.app-sync-succeeded: |
    slack:
      attachments:
        - title: Application {{.app.metadata.name}} sync succeeded
          color: good
          text: |
            Application {{.app.metadata.name}} sync succeeded at {{.app.status.operationState.finishedAt}}.
