apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: argocd/slack/webhook
