apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-webhook: "https://hooks.slack.com/services/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"