apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  slack-token: xoxe.xoxp-1-Mi0yLTkyMzg3MTU0NzQ0MzgtOTIzODcxNTUyMjQwNi05MjMzMjI0OTkzMzUxLTkyMzMyMjUwMDAzNzUtNjBmZTdiNzgwODNkOTI2YmU4OWYwZDc4NWY4NTJkZDc2MGE4YmFhNmZkOGJmNWFmOWFiMzQwYzEzZjllYzkyOA