apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nodejs-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "true"

spec:
  project: default

  source:
    repoURL: https://github.com/borayldrm22/automation-project.git
    targetRevision: HEAD
    path: my-nodejs-app  # <-- this should be your Helm chart folder
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
