apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-slack-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store      # Make sure you have this SecretStore configured for AWS
    kind: SecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: slack-webhook-url
      remoteRef:
        key: argocd/slackwebhook    # your secret name in AWS Secrets Manager
        property: slack-webhook-url # the key inside the secret, if you stored it with that key
