apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: slack-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: argocd/slack/webhook  # name of your AWS Secrets Manager secret
        property: aws/secretsmanager          # the key inside the secret
