apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        # Use IRSA if on EKS, or accessKeyID/secretAccessKey for local
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
          audience: sts.amazonaws.com
